version: '3.3'

services:
  node:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - /app/node_modules
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app_network

  db:
    build: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_library
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
