version: '3.3'

services:
  node:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    command: npm run start:dev
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    build: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_library
