version: '3.3'

services:
  node:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    volumes:
      - ..:/app
      - /app/node_modules
    restart: always
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    networks:
      - app_network

  db:
    build: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_library
    volumes:
      - "./volumes/postgres/data/:/var/lib/postgresql/data"
      - "./volumes/postgres/logs/:/var/log/postgresql/"
    ports:
      - ${DOCKER_DB_PORT}:${DOCKER_DB_PORT}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
